#!/usr/bin/env bash
set -euo pipefail
# Capital Glass Intelligence Hub scout lane — generated by sync:intelligence-hub-scout-hooks
if [ -f "${HOME}/.config/capital-glass/cursor-wsl.env" ]; then
  # shellcheck disable=SC1091
  source "${HOME}/.config/capital-glass/cursor-wsl.env"
fi
MCP_ROOT="${CG_APPBUILDER_MCP_ROOT:-${CG_REPOS_ROOT:-$HOME/repos}/CG-AppBuilder-MCP}"
exec node "${MCP_ROOT}/agent-packs/three-way-agent/hooks/intelligence-hub-scout-inject.mjs"
